---
- hosts: 172.31.41.8
  become: yes
  tasks: 
  - name: i want to execute linux command
    command:
      cmd: hostname -f
    register: myresult
  - name: i want to display myresult
    debug: 
      msg: "{{myresult}}"

  - name: i want to execute linux command2
    command:
      cmd: hostname -i
    register: myresult1
  - name: i want to display myresult
    debug: 
      msg: "{{myresult2}}"