---
- hosts: 172.31.41.8
  become: yes
  tasks: 
  - name: i want to execute linux command
    command:
      cmd: hostname -f
    register: myresult
  - name: i want to display myresult
    debug: 
      msg: "{{myresult}}"

  - name: i want to execute linux 2nd command
    command:
      cmd: hostname -i
    register: myresult1
  - name: i want to display myresult1
    debug: 
      msg: "{{myresult1}}"
  - name: i want to install git
    apt: 
      name: git
      state: present
      when: myresult.stderr== ""
  - name: i want to install tree
    apt: 
      name: tree
      state: present
      when: myresult.stderr != ""