---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i want to install webserver on all ubuntu ansible nodes
    apt: 
      name: "{{mywebpackforubuntu}}"
      state: present
    when: ansible_os_family=="Debian"
  
  - name: start webserver on ubuntu ansible nodes
    service: 
      name: "{{mywebpackforubuntu}}"
      state: started
    when: ansible_os_family=="Debian"

  - name: i want to install webserver on Redhat ansible nodes
    yum:
      name: "{{mywebpackforRedHat}}"
      state: present
    when: ansible_os_family=="RedHat"

  - name: start webserver on Redhat ansible nodes
    service: 
      name: httpd
      state: started
    when: ansible_os_family=="RedHat"