---
- name: deploy jenkins as application
  get_url:
    url: https://get.jenkins.io/war-stable/2.303.2/jenkins.war
    dest: /opt/tomcat/webapps/jenkins.war
    force_basic_auth: yes

- name: deploy java application
  get_url:
    url: https://raw.githubusercontent.com/AKSarav/SampleWebApp/master/dist/SampleWebApp.war
    dest: /opt/tomcat/webapps/SampleWebApp.war
    force_basic_auth: yes
