---
# create tomcat user & group
- name: create group
  group: 
    name: tomcat
    state: present
- name: create user
  group: 
    name: tomcat
    shell: /bin/true
    group: tomcat
    home: /opt/tomcat