---
- name: copy tomcat user file into node sides
  template:
    src: templates/mytomuser.j2
    dest: /opt/tomcat/conf/tomcat-users.xml

- name: tomcat context file create
  template:
    src: templates/mytomcontext.j2
    dest:  /opt/tomcat/webapps/manager/META-INF/context.xml

- name: tomcat host context file create
  template:
    src: templates/mytomhostcontext.j2
    dest:  /opt/tomcat/webapps/host-manager/META-INF/context.xml